### ISSUE TITLE
Is this considered a TS Plugin?

### ISSUE THREAD

**Issue by brian428** [dropbox/ts-transform-import-path-rewrite#1]
Can this be used in the plugins block in tsconfig? Or does it only work if you manually run it via `compile()`?

**Comment by longlho** [comment]
Unfortunately this cannot be used as a plugin bc plugin right now [cannot change how the compiler emits JavaScript.](https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin)

>>>Examples of things language plugins cannot do:

Add new custom syntax to TypeScript
Change how the compiler emits JavaScript
Customize the type system to change what is or isn't an error when running tsc

**Comment by brian428** [comment]
Darn, but thanks for the response!
