### ISSUE TITLE
Add example to readme to use in ttypescript

### ISSUE THREAD

**Issue by cevek** [dropbox/ts-transform-import-path-rewrite#2]
https://github.com/cevek/ttypescript

in tsconfig.json
```
{
   compilerOptions: {
     plugins: [
       {transform: "ts-transform-import-path-rewrite", import: "transformDts", type: "config", ...pluginOptions}
    ]
   }
}
```

**Comment by longlho** [comment]
PR's welcome :) I've never used ttypescript before. This transformer also supports `afterDeclarations` as well.

**Comment by stavalfi** [comment]
@cevek  that doesn't work. I may not use it correctly. can you please give a small repo as an example?
