### ISSUE TITLE
TypeScript 4.x support

### ISSUE THREAD

**Issue by AndrewLeedham** [dropbox/ts-transform-import-path-rewrite#236]
I am currently using this package with 3.9.x. I am curious if support for 4.x is planned, seems like the dependabot PR is failing tests: https://github.com/dropbox/ts-transform-import-path-rewrite/pull/233

**Comment by longlho** [comment]
Yeah I'll take a look later

**Comment by AndrewLeedham** [comment]
Seemed fairly straight forward, so I took a swing at it. Let me know what you think.

**Comment by longlho** [comment]
`0.3.0` should have this fix. Thanks!
